r25840 | kobus | 2020-09-30 13:50:24 -0700 (Wed, 30 Sep 2020) | 2 lines
Bits and pieces of cleanup; locking build-2 (conservatively)

Recorded result of commands processed by svn in /home/ivilab/repo_sync/ivilab_src_local/src/Make:
Updating '.':
U    Makefile-program
U    init_compile
U    util/Makefile
U    Makefile-library
U    scripts/ivi_lock_create
U    scripts/make_ivi
U    scripts/build-2
U    scripts/Makefile
U    Makefile
Updated to revision 25840.

diff --git a/Make/scripts/build-2 b/Make/scripts/build-2
--- a/Make/scripts/build-2
+++ b/Make/scripts/build-2
@@ -530,10 +530,11 @@ while ($count <=  ${num_args})
         setenv BUILD_BIN_PATH "${MAKE_BIN_PATH}"
         set arg = "bin"
     else if ("${arg}" == "ivi") then
-        set make_cmd = "${MAKE_SCRIPT_PATH}make_ivi ivi ivi_cpp skip_depend skip_regress skip_no_libs skip_prog_no_libs skip_prog_dirs"
+        set make_cmd = "${MAKE_SCRIPT_PATH}make_ivi IVI IVI_cpp code doc tags skip_depend skip_regress skip_no_libs skip_prog_no_libs skip_prog_dirs"
         if ($?DRY_RUN) then
             echo "DRY: ${make_cmd}"
         else
+            ${VERBOSE_ECHO} "Script build-2 executing: ${make_cmd}"
             ${make_cmd}
             if (${status}) exit 1
         endif
@@ -544,6 +545,7 @@ while ($count <=  ${num_args})
         if ($?DRY_RUN) then
             echo "DRY: ${make_cmd}"
         else
+            ${VERBOSE_ECHO} "Script build-2 executing: ${make_cmd}"
             ${make_cmd}
             if (${status}) exit 1
         endif 
@@ -554,6 +556,7 @@ while ($count <=  ${num_args})
         if ($?DRY_RUN) then
             echo "DRY: ${make_cmd}"
         else
+            ${VERBOSE_ECHO} "Script build-2 executing: ${make_cmd}"
             ${make_cmd}
             if (${status}) exit 1
         endif
@@ -564,6 +567,7 @@ while ($count <=  ${num_args})
         if ($?DRY_RUN) then
             echo "DRY: ${make_cmd}"
         else
+            ${VERBOSE_ECHO} "Script build-2 executing: ${make_cmd}"
             ${make_cmd}
             if (${status}) exit 1
         endif
@@ -574,6 +578,7 @@ while ($count <=  ${num_args})
         if ($?DRY_RUN) then
             echo "DRY: ${make_cmd}"
         else
+            ${VERBOSE_ECHO} "Script build-2 executing: ${make_cmd}"
             ${make_cmd}
             if (${status}) exit 1
         endif
@@ -584,6 +589,7 @@ while ($count <=  ${num_args})
         if ($?DRY_RUN) then
             echo "DRY: ${make_cmd}"
         else
+            ${VERBOSE_ECHO} "Script build-2 executing: ${make_cmd}"
             ${make_cmd}
             if (${status}) exit 1
         endif
@@ -939,6 +945,32 @@ if ($?LOG_MAKE) then
 else 
     set make_log_file = '/dev/null'
 endif 
+
+# The next (long) block of code can lead to removing of build files if the build
+# fails. This can take out other running builds. So we lock being in this file.
+# This solution is far more conservative than needed. What we need to be sure of
+# is that if we do either "clean_local" or "clean_global", that we check that
+# there are no other build processes running, and wait if there are any. We
+# would need to check if any of them are dead or too old. This might look like
+# an implementation of a shared lock with R/W options.  This is not so hard to
+# implement, but will take a bit of time, so leaving it for later. TODO 
+
+# Until we upgrade the locking solution as above, we should be careful not to
+# call this script recursively. If we do, it will exit due to deadlock risk.
+# This means that we cannot do "cd xxx; make" in a makefile, as this will call
+# this script via the makefile Makefile. But we can do things like this hack in
+# Makefile-library (the specification of a makefile other than Makefile dodges
+# going through this script:
+#     $(IVI_CD) $(IVI_SRC_PATH)IVI_cpp; ${IVI_MAKE_JOB_CLIENT} -f Makefile-2 doxygen
+#
+
+set lock_label = "build-2"
+setenv EXIT_ON_DEADLOCK
+source ${MAKE_SCRIPT_PATH}check_for_deadlock
+if (${status}) exit 1
+
+${MAKE_SCRIPT_PATH}ivi_lock_create 2000 "${lock_label}"
+if (${status}) exit 1
 
 set exit_status = 0
 set try_count = 1
@@ -1442,9 +1474,16 @@ while (${try_count} <= 4)
                         else
                             if ($?LOG_MAKE) set make_log_file = "${MAKE_LOG_PATH}make_c2man_bin_${try_count}.res"
 
-                            # We only want to make the documentation tools using the default C
-                            # compiler and production mode. The setting of IVI_CC to empty asks
-                            # init_compile to choose the compiler. 
+                            # We only want to make the documentation tools
+                            # using the default C compiler and production mode.
+                            # The setting of IVI_CC to empty asks init_compile
+                            # to choose the compiler. 
+                            # 
+                            # Unlike most makes, we do not (can not) use
+                            # Makefile-2 as c2man is a special case where the
+                            # Makefile is manually constructed. We might change
+                            # it at some point to be more consistent with other
+                            # program dirs. 
                             #
                             (   setenv IVI_CC ""; setenv PRODUCTION 1; setenv BUILD_BIN_PATH "${MAKE_BIN_PATH}"; \
                                 source ${MAKE_PATH}init_compile; \
@@ -1465,7 +1504,7 @@ while (${try_count} <= 4)
                         ${VERBOSE_ECHO} "Script build-2 is building utilities in ${cwd}." 
 
                         if ($?DRY_RUN) then
-                            echo "DRY: (setenv IVI_CC ''; setenv PRODUCTION 1; setenv BUILD_BIN_PATH ${MAKE_BIN_PATH}; source ${MAKE_PATH}init_compile; ${IVI_MAKE_SERIAL} bin)"
+                            echo "DRY: (setenv IVI_CC ''; setenv PRODUCTION 1; setenv BUILD_BIN_PATH ${MAKE_BIN_PATH}; source ${MAKE_PATH}init_compile; ${IVI_MAKE_SERIAL} -f Makefile-2 bin)"
                         else
                             if ($?LOG_MAKE) set make_log_file = "${MAKE_LOG_PATH}make_util_bin_${try_count}.res"
 
@@ -1476,7 +1515,7 @@ while (${try_count} <= 4)
                             (   setenv IVI_CC ""; setenv PRODUCTION 1; setenv BUILD_BIN_PATH "${MAKE_BIN_PATH}"; \
                                 source ${MAKE_PATH}init_compile; \
                                 if ("${IVI_CC}" != "${save_ivi_cc}") ${WARN_ECHO} "Switching compiler from ${save_ivi_cc} to ${IVI_CC} for doc utilities"; \
-                                ${IVI_MAKE_SERIAL} bin |& ${suppress_jobserver_msg} |& ${IVI_TEE} ${make_result_temp_file} |& ${IVI_TEE} ${make_log_file} \
+                                ${IVI_MAKE_SERIAL} -f Makefile-2 bin |& ${suppress_jobserver_msg} |& ${IVI_TEE} ${make_result_temp_file} |& ${IVI_TEE} ${make_log_file} \
                             ) 
                             set make_status = ${status}
 
@@ -1580,6 +1619,8 @@ while (${try_count} <= 4)
             if (${test_arg}) then
     #           # All this stuff from before should not be necessary. Kill it
     #           eventually. Claim made 12/13/2019.
+    #
+    #           If we keep it, must remove the direct exits! 
     #
     #             if (! -e "Makefile-test-depend") then
     #                 set make_tmp_dir = "${TMPDIR}/${USER}/Makefile-test-depend/make"
@@ -1715,6 +1756,7 @@ while (${try_count} <= 4)
                 set bad_arg  = `${IVI_GREP} -c "No rule to make target .${arg}.\." < "${make_result_temp_file}"`
 
                 if (${bad_arg}) then
+                    ${P_STDERR} "Possibly the target (${arg}) is mispelled."
                     set exit_status = 1
                 else 
                     set build_issue = `${IVI_GREP} -c 'No rule to make target' < "${make_result_temp_file}"`
@@ -1834,6 +1876,8 @@ if ( ! $?IVI_QUIET ) then
     echo " "
 
 endif 
+
+${MAKE_SCRIPT_PATH}ivi_lock_remove build-2 
 
 exit ${exit_status}
 
diff --git a/Make/scripts/make_ivi b/Make/scripts/make_ivi
--- a/Make/scripts/make_ivi
+++ b/Make/scripts/make_ivi
@@ -98,14 +98,14 @@
 #          then the script will continue if possible, and exit with 1 if any
 #          errors were encountered along the way.  
 #
-# |     ivi 
+# |     IVI 
 #          This builds code and tags (depending on those options) in lib/IVI.
 #          Different than the option "lib" we are not focussed on building an
 #          exportable version. We do this building relatively early on, which
 #          also allows library Makefiles and code to be built faster due to more
 #          parallelism, provided that we do not clean. 
 #
-# |     ivi_cpp
+# |     IVI_CPP
 #          This builds code and tags (depending on those options) in
 #          lib/IVI_cpp. Different than the option "lib_cpp", we are not focussed
 #          on building an exportable version. We do this building relatively
@@ -166,6 +166,12 @@
 #           constructed. This is mostly useful for debugging. Normally, one
 #           would want this test if the code was really being exported.  
 # 
+# |      code
+#          This requests building code (compiling). The default is to do so, so
+#          this option is not necessary, but it is available for future changes,
+#          and including it in calls to make_ivi in scripts can make the
+#          intention more clear. 
+#  
 # |      skip_code
 #           This disables compiling code where not needed. We still compile
 #           tools, and code might be compiled as a consequence of other
@@ -473,8 +479,9 @@ foreach option ($*)
     else if (("${option}" == "ctags") || ("${option}" == "tags")) then
         set do_ctags = 1
         set do_something = 1
-    else if ("${option}" == "compile") then
+    else if (("${option}" == "compile") || ("${option}" == "code")) then
         set do_something = 1
+        set skip_code = 0 
     else if ("${option}" == "doc") then
         set do_doc = 1
         set do_something = 1
@@ -503,10 +510,10 @@ foreach option ($*)
         set export_src_tree = 1
     else if ("${option}" == "skip_export_src_tree") then
         set export_standalone = 0
-    else if ("${option}" == "ivi") then
+    else if ("${option}" == "IVI") then
         set do_ivi = 1
         set do_something = 1
-    else if ("${option}" == "ivi_cpp") then
+    else if ("${option}" == "IVI_CPP") then
         set do_ivi_cpp = 1
         set do_something = 1
     else if ("${option}" == "lib") then
@@ -644,7 +651,7 @@ else
         set export_prog_dirs = "${export_prog_dirs} tools/ncuts_modified"
     endif 
 
-    set prog_dirs = "${export_prog_dirs} examples/templates/* examples/ivi projects/words_and_pictures/it projects/words_and_pictures/it/util examples/segment tools/kjb_tools tools/kjb_util tools/kjb_math projects/color/var_illum projects/SLIC/slide_match projects/SLIC/slide_match_v02" 
+    set prog_dirs = "${export_prog_dirs} examples/templates/* examples/IVI projects/words_and_pictures/it projects/words_and_pictures/it/util examples/segment tools/kjb_tools tools/kjb_util tools/kjb_math projects/color/var_illum projects/SLIC/slide_match projects/SLIC/slide_match_v02" 
 
     if ("${OS}" == "linux_386") then
         #
@@ -1059,7 +1066,7 @@ if (! ${skip_code}) then
                     if (! ${keep_going}) goto end_of_script
                 endif
             else
-                echo "Script make_ivi skipping make depend in `pwd` due to options."
+                echo "Make_ivi: skipping make depend in `pwd` due to option 'skip_depend'."
             endif
 
             foreach production (0 1)
@@ -1182,12 +1189,12 @@ pushd lib > /dev/null
                 ${IVI_MAKE_JOB_CLIENT} depend 
 
                 if (${status}) then
-                    echo "Make depend failed in ${cwd}" | tee -a ${error_file}
+                    echo "Make_ivi: Make depend failed in ${cwd}" | tee -a ${error_file}
                     set exit_status = 1
                     if (! ${keep_going}) goto end_of_script
                 endif
             else
-                echo "Script make_ivi skipping make depend in `pwd` due to options."
+                echo "Make_ivi: Skipping make depend in `pwd` due to options."
             endif
 
             if (! ${skip_code}) then
@@ -1285,7 +1292,7 @@ pushd lib > /dev/null
                 # This seems to do nothing?
                 set sub_lib_dir = "${sub_lib_dir}"
             else
-                echo "Make_ivi: Skipping make in `pwd` due to options."
+                echo "Make_ivi: Skipping make in `pwd` due to option skip_code."
             endif
 
             if (($do_doc) && ("${is_cpp_dir}" == "") && (! -e "SKIP_C2MAN"))  then
@@ -1297,7 +1304,7 @@ pushd lib > /dev/null
                     if (! ${keep_going}) goto end_of_script
                 endif
             else
-                echo "Make_ivi: Skipping doc in `pwd` due to options."
+                echo "Make_ivi: Skipping doc in `pwd` due to options (do_doc==${do_doc})."
             endif
 
             if ($do_ctags) then
@@ -1313,7 +1320,7 @@ pushd lib > /dev/null
                     ### echo lib/${sub_lib_dir}/tags >> ${src_dist_file_dir}/src_dist_files
                 endif
             else
-                echo "Make_ivi: Skipping ctags in `pwd` due to options."
+                echo "Make_ivi: Skipping ctags in `pwd` due to option do_ctags==${do_ctags}."
             endif
 
             if ($collect_files) then
@@ -1477,6 +1484,8 @@ pushd lib > /dev/null
                                 setenv IVI_PREFER_CXX 0
                                 unsetenv IVI_CC
                             endif
+                        else
+                            echo "Make_ivi: Skipping make in `pwd` due to option skip_code."
                         endif
 
                         if (${export_test_code}) then
@@ -1497,6 +1506,8 @@ pushd lib > /dev/null
                                 #
                                 ### echo lib/${sub_lib_dir}/${sub_lib_test_dir}/tags >> ${src_dist_file_dir}/${tar_list_file}
                             endif
+                        else
+                            echo "Make_ivi: Skipping ctags in `pwd` due to option do_ctags==${do_ctags}."
                         endif 
 
                         if (($do_archive) || (($do_export) && ($export_lib_test_dirs))) then
@@ -2170,8 +2181,12 @@ endif
 
 if ($do_lib) then
     echo ------------------------------------------------------------
-    echo Make_ivi: Building the exported version of the ivi C library
+    echo Make_ivi: Building the exported version of the IVI C library
     echo ------------------------------------------------------------
+
+    ${P_STDERR} 
+    ${P_STDERR} "This is probably broken and has not been run recently."
+    ${P_STDERR}
 
     pushd IVI > /dev/null
 
@@ -2218,10 +2233,10 @@ if ($do_lib) then
     set sub_libs_needed = `cat Include_lines/sub_libs_needed`
 
     foreach include_path (${include_paths})
-        set backup_dir = ${include_path}/ivi/backups/$time_stamp
+        set backup_dir = ${include_path}/IVI/backups/$time_stamp
         ${IVI_MKDIR} ${backup_dir}
 
-        rsync -au --backup --backup-dir=$backup_dir ivi.h ${include_path}/ivi
+        rsync -au --backup --backup-dir=$backup_dir IVI.h ${include_path}/IVI
 
         foreach dir (${sub_libs_needed})
             if (! -d "${IVI_LIB_PATH}${dir}") then 
@@ -2234,17 +2249,17 @@ if ($do_lib) then
             echo Make_ivi: Updating includes for ${IVI_LIB_PATH}$dir in ${include_path}
             echo -----------------------------------------------------------------
 
-            ${IVI_MKDIR}  ${include_path}/ivi/${dir}
-            set backup_dir = ${include_path}/ivi/backups/${time_stamp}/${dir}
-            rsync -au --backup --backup-dir=${backup_dir} ${IVI_LIB_PATH}${dir}/*.h ${include_path}/ivi/${dir}
+            ${IVI_MKDIR}  ${include_path}/IVI/${dir}
+            set backup_dir = ${include_path}/IVI/backups/${time_stamp}/${dir}
+            rsync -au --backup --backup-dir=${backup_dir} ${IVI_LIB_PATH}${dir}/*.h ${include_path}/IVI/${dir}
         end
 
         pushd ${include_path} > /dev/null
 
-        # ln -s -f ${include_path}/ivi/* .
-        ln -s -f ivi/* .
+        # ln -s -f ${include_path}/IVI/* .
+        ln -s -f IVI/* .
         if (${status}) then
-            echo "Command failed in `pwd`: ln -s -f ivi/* ." | tee -a ${error_file}
+            echo "Command failed in `pwd`: ln -s -f IVI/* ." | tee -a ${error_file}
             set exit_status = 1
             goto end_of_script
         endif 
@@ -2292,6 +2307,15 @@ if ($do_lib_cpp) then
     echo Make_ivi: Building the exported version of the IVI C++ library
     echo --------------------------------------------------------------
 
+    ${P_STDERR} 
+    ${P_STDERR} "This is probably broken and has not been run recently."
+    ${P_STDERR}
+
+    # Why, for example, do we use IVI.h? Are we building a combined C/C++
+    # library, which we do anyway. It may be confusing (or wrong) to use IVI in
+    # place of IVI_copp below. 
+
+    
     pushd IVI_cpp > /dev/null
 
     setenv PRODUCTION 1
@@ -2336,10 +2360,10 @@ if ($do_lib_cpp) then
     set sub_libs_needed = `cat Include_lines/sub_libs_needed`
 
     foreach include_path (${include_paths})
-        set backup_dir = ${include_path}/ivi/backups/$time_stamp
+        set backup_dir = ${include_path}/IVI/backups/$time_stamp
         ${IVI_MKDIR} ${backup_dir}
 
-        rsync -au --backup --backup-dir=$backup_dir ivi.h ${include_path}/ivi
+        rsync -au --backup --backup-dir=$backup_dir IVI.h ${include_path}/IVI
 
         foreach dir (${sub_libs_needed})
             if (! -d "${IVI_LIB_PATH}${dir}") then 
@@ -2352,17 +2376,17 @@ if ($do_lib_cpp) then
             echo Make_ivi: Updating includes for ${IVI_LIB_PATH}$dir in ${include_path}
             echo -----------------------------------------------------------------
 
-            ${IVI_MKDIR}  ${include_path}/ivi/${dir}
-            set backup_dir = ${include_path}/ivi/backups/${time_stamp}/${dir}
-            rsync -au --backup --backup-dir=${backup_dir} ${IVI_LIB_PATH}${dir}/*.h ${include_path}/ivi/${dir}
+            ${IVI_MKDIR}  ${include_path}/IVI/${dir}
+            set backup_dir = ${include_path}/IVI/backups/${time_stamp}/${dir}
+            rsync -au --backup --backup-dir=${backup_dir} ${IVI_LIB_PATH}${dir}/*.h ${include_path}/IVI/${dir}
         end
 
         pushd ${include_path} > /dev/null
 
-        # ln -s -f ${include_path}/ivi/* .
-        ln -s -f ivi/* .
+        # ln -s -f ${include_path}/IVI/* .
+        ln -s -f IVI/* .
         if (${status}) then
-            echo "Command failed in `pwd`: ln -s -f ivi/* ." | tee -a ${error_file}
+            echo "Command failed in `pwd`: ln -s -f IVI/* ." | tee -a ${error_file}
             set exit_status = 1
             goto end_of_script
         endif 
