r25833 | kobus | 2020-09-26 15:52:37 -0700 (Sat, 26 Sep 2020) | 2 lines
Added support for all_tags.

Recorded result of commands processed by svn in /home/ivilab/repo_sync/ivilab_src_local/src/Make:
Updating '.':
U    Makefile-program
U    scripts/build_library_makefile_depend
U    scripts/do_ctags
U    scripts/build_program_makefile_depend
U    scripts/build-2
U    Makefile-library.gmake
U    init_scripts
U    Makefile-library
U    Makefile-defs
Updated to revision 25833.

diff --git a/Make/scripts/do_ctags b/Make/scripts/do_ctags
--- a/Make/scripts/do_ctags
+++ b/Make/scripts/do_ctags
@@ -24,18 +24,25 @@ else if ("${num_args}" == 1) then
     endif 
 endif 
 
-(${IVI_LS} -1 *.[ch] |& grep -v "No match" > tag_files) >& /dev/null
+${MAKE_SCRIPT_PATH}stream_file_names -s -h  > tag_files
+if (${status}) exit 1 
 
 if (-e Include_lines/sub_libs_needed) then
     set sub_libs_needed = `/bin/cat Include_lines/sub_libs_needed`
 
     foreach sub_lib_needed ($sub_libs_needed)
         if (-d ${IVI_LIB_PATH}/${sub_lib_needed}) then
-             ${IVI_LS} -1 ${IVI_LIB_PATH}/${sub_lib_needed}/*.[ch]  |& grep -v "No match"  >> tag_files
+            # ${IVI_LS} -1 ${IVI_LIB_PATH}/${sub_lib_needed}/*.[ch]  |& grep -v "No match"  >> tag_files
+            ${MAKE_SCRIPT_PATH}stream_file_names -s -h ${IVI_LIB_PATH}/${sub_lib_needed} >> tag_files
+            if (${status}) exit 1 
         else if (-d lib/${sub_lib_needed}) then
-             ${IVI_LS} -1 lib/${sub_lib_needed}/*.[ch]  |& grep -v "No match"  >> tag_files
+            # ${IVI_LS} -1 lib/${sub_lib_needed}/*.[ch]  |& grep -v "No match"  >> tag_files
+            ${MAKE_SCRIPT_PATH}stream_file_names -s -h lib/${sub_lib_needed} >> tag_files
+            if (${status}) exit 1 
         else if (-d ../../lib/${sub_lib_needed}) then
-             ${IVI_LS} -1 ../../lib/${sub_lib_needed}/*.[ch]  |& grep -v "No match"  >> tag_files
+            # ${IVI_LS} -1 ../../lib/${sub_lib_needed}/*.[ch]  |& grep -v "No match"  >> tag_files
+            ${MAKE_SCRIPT_PATH}stream_file_names -s -h ../../lib/${sub_lib_needed} >> tag_files
+            if (${status}) exit 1 
         endif
     end
 endif 
@@ -56,13 +63,22 @@ else
     # Testing new ctags c++ support (probably these new flags won't work with GNU ctags, either)
     ${IVI_CTAGS} -a -L tag_files --c++-kinds=+p --fields=+iaS --extra=+q -o tags
     if (${status}) then
-        echo "ctags failed in script do_ctags."
+        echo "ctags failed making tag file 'tags' in script do_ctags."
         echo "Possibly ctags on this machine is an old flavor that we don't care about."
         set exit_status = 1
     endif 
 endif 
 
-${IVI_RM} tag_files >& /dev/null
+if (-e Include_lines/all_tag_files) then
+    ${IVI_CTAGS} -a -L Include_lines/all_tag_files --c++-kinds=+p --fields=+iaS --extra=+q -o all_tags
+    if (${status}) then
+        echo "ctags failed making tag file 'all_tags' in script do_ctags."
+        echo "Possibly ctags on this machine is an old flavor that we don't care about."
+        set exit_status = 1
+    endif 
+endif 
+
+${IVI_RM} tag_files 
 
 exit ${exit_status}
 
