r25709 | kobus | 2020-08-10 12:31:01 -0700 (Mon, 10 Aug 2020) | 1 line
Lazy

Recorded result of commands processed by svn in /home/ivilab/repo_sync/ivilab_src_local/src/Make:
Updating '.':
U    scripts/ivi_lock_remove
A    scripts/test/lock_and_sleep
A    scripts/test/test_ivi_milli_sleep
A    scripts/test/test_ivi_lock_timeout
A    scripts/test/test_ivi_lock_process_gone
A    scripts/test/test_ivi_deadlock
U    scripts/test/test_ivi_lock_2_helper
U    scripts/test/increment_file_line
A    scripts/test/lock_and_die
A    scripts/atomic_echo_2
A    scripts/atomic_echo_3
A    scripts/atomic_echo
U    scripts/ivi_lock_create
Updated to revision 25709.

diff --git a/Make/scripts/ivi_lock_create b/Make/scripts/ivi_lock_create
--- a/Make/scripts/ivi_lock_create
+++ b/Make/scripts/ivi_lock_create
@@ -9,7 +9,7 @@
 # Description:
 #     This is a simple script for locking blocks of script code that is not
 #     conveniently expressed as a command (otherwise use ivi_lock). It works
-#     much like lockfile-create, and in fact, is implemented using
+#     much like lockfile-create, and in fact, is might be implemented using
 #     lockfile-create if it is available. The main justification for this script
 #     is that locking is not universally available. Most notably good locking
 #     facilities are not available in the mac OS. Hence, this script also
@@ -71,7 +71,7 @@ if ($?IVI_SET_ECHO) then
     set echo
 endif 
 
-${VERBOSE_ECHO} "${VERBOSE_INDENT}Script ivi_lock_create process $$ called with args: $*."
+${VERBOSE_ECHO} "${VERBOSE_INDENT}Script ivi_lock_create called with args: $*."
 
 if ($# < 2) then
     ${P_STDERR} "Script ivi_lock_create needs at least two arguments."
@@ -100,22 +100,21 @@ if ($?IVI_DONT_LOCK) then
     exit 0
 endif
 
-# We work in units of 0.01s. 
+# We work in units of .01s. 
 @ max_time_to_wait *= 100
 
 set lock_label = "$2"
 
 set exit_status = 0
 
-set noclober
+set noclobber
 
 source ${MAKE_SCRIPT_PATH}set_lockfile_name
 if (${status}) exit ${status} 
 
 onintr ivi_lock_create_bail
 
-${VERBOSE_ECHO} "${VERBOSE_INDENT}Script ivi_lock_create process $$ running lock_create ${lock_label} in ${cwd}"
-${VERBOSE_ECHO} "${VERBOSE_INDENT}    on behalf of process ${requesting_pid} using lockfile '${lock_file}'"
+${VERBOSE_ECHO} "${VERBOSE_INDENT}Script ivi_lock_create using lock file ${lock_file} for ${requesting_pid} in ${cwd}"
 
 if ("${IVI_LOCK_PROGS_METHOD}" == "lockfile-progs") then
     echo "UNTESTED: Process $$ running lock_create ${lock_label} in `pwd` using lockfile-progs"
@@ -134,184 +133,192 @@ else
     # often (e.g., mac) we do not have a good solution. The following is better
     # than nothing.
 
-    ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process $$ running lock_create ${lock_label} in `pwd` using IVI locking system."
+    ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process ${requesting_pid} handler running lock_create ${lock_label} in ${cwd} using IVI locking system."
 
     set start_time = `date +%H:%M:%S`
 
-    # Reduce the chances of everyone wanting to start at the same time.
-    # I do not know how likely this is to fail, or even to return success
-    # without doing the right thing, but it seems to work on the mac. 
-
-    set x = $$ ; @ x %= 100 ; set sleep_time = "0.0${x}"
-    ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process $$ sleeping for ${sleep_time} seconds"
-    sleep ${sleep_time}
-
-    if (${status}) then
-        ${P_STDERR} "Fractional sleep failed in ivi_lock_create." 
-        set exit_status = 1
-        goto cleanup
-    endif
-
     set time_waited = 0
 
+    set got_it = 0
+
+    set zero = ""
+    @ x = $$ % 100; @ y = $x % 10;  @ z = $x / 10; @ w = 10 * $y + $z; @ w /= 3
+    if ($w < 10) set zero = "0" 
+    set sleep_time = "0.${zero}${w}"
+
+    set id = "${requesting_pid}"
+    set id = "${SHORT_HOST}-${requesting_pid}"
+
     while (1) 
+        # Reduce the chances of everyone wanting to start at the same time.
+        # I do not know how likely this is to fail, or even to return success
+        # without doing the right thing, but it seems to work on the mac. 
+
+        ${VERBOSE_ECHO} "${VERBOSE_INDENT}Lock handler for ${id} sleeping for ${sleep_time} seconds"
+        sleep ${sleep_time}
+        @ time_waited += ${w}
+
+        if (${status}) then
+            ${P_STDERR} "Fractional sleep failed in ivi_lock_create." 
+            set exit_status = 1
+            goto cleanup
+        endif
+
         if (! -e "${lock_file}") then
-            # Unlike some of the similar lines below, we do not have an '!'
-            # after the '>', as we want to fail due to noclober.
-            #
-            echo ${requesting_pid} > ${lock_file}
+            ${MAKE_SCRIPT_PATH}atomic_echo ${lock_file} "${id}" 
+            set atomic_echo_status =  ${status}
 
-            # Someone else might have just written the file. 
-            if (${status}) then
-                #  I have not found a safe way to ignore error output. 
-                set apparent_lock_owner = `cat ${lock_file}`
-                if (${status}) then
-                    echo "Someone might have snuck in before me (${requesting_pid}). Sleeping."
-                else
-                    echo "Process ${apparent_lock_owner} snuck in before me (${requesting_pid}). Sleeping."
-                endif 
-
-                set x = ${requesting_pid} ; @ x %= 100 ; set sleep_time = "0.${x}"
-
-                @ time_waited += $x
-
-                ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process $$ sleeping for ${sleep_time} seconds for ${requesting_pid}."
-
-                sleep ${sleep_time}
-
-                if (${status}) then
-                    ${P_STDERR} "Fractional sleep failed in ivi_lock_create." 
-                    set exit_status = 1
-                    goto cleanup
-                endif
-
+            if (${atomic_echo_status}) then
+                ${VERBOSE_ECHO} "${VERBOSE_INDENT}Lock handler for ${requesting_pid} failed to get lock. Geting back in the queue."
                 continue
-            endif 
-
-            ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process $$ has tentatively set lock file ${lock_file} for ${requesting_pid}."
-            # ps -l $$
+            else 
+                ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process ${requesting_pid} lock handler has set lock file ${lock_file} (contents `cat ${lock_file}`)."
+                set got_it = 1
+            endif
         else 
             set count = 0
-            set got_it = 0
 
             while (-e "${lock_file}")
-                #  I have not found a safe way to ignore error output. 
-                set lock_proc = `cat ${lock_file}`
-
-                # Happens! But just grabbing the lock is not safe. Since we do
-                # not have an atomic command capability, nothing is really safe.
-                # But we can improve our odds by taking advantage of noclober,
-                # which we do by going back out to the outer loop.
-
-                if ($status) then 
-                    # echo ${requesting_pid} >! ${lock_file}
-                    echo "Lock file ${lock_file} disappeared! Getting back in the queue."
-                    break
-                endif 
-
-                # If the contents is bogus, then the ps below will fail. But if
-                # it is empty, ps will not fail. So we check here. 
-                #
-                if ("${lock_proc}" == "") then
-                    echo ${requesting_pid} >! ${lock_file}
-                    echo "Cannot read a process id from lock file. Assuming it is stale."
-                    set got_it = 1
-                    break
-                endif 
-
-                ${VERBOSE_ECHO_2} "${VERBOSE_INDENT}Lock file ${lock_file} exists."
-
                 # Check up on the process holding the lock every so often. We
                 # used to do it every time through the loop, but we then
                 # expected that this lead to spending too much time in the 'ps'
                 # caommand. However, it turned out that the issue was from
                 # build_sub_libs_needed, but it seems that this is a good
                 # optimization for some circumstances anyway. 
-                
-                @ block_cycle = ${count} % 10
+               
+                @ block_cycle = ${count} % 5
+                @ block_cycle = ${count} % 1
 
                 if (${block_cycle} == 0) then
-                    ${VERBOSE_ECHO_2} "${VERBOSE_INDENT}Process $$ checking on lock file process ${lock_proc} on iteration ${count}." 
+                    #  I have not found a safe way to ignore error output. 
+                    set lock_id = `cat ${lock_file}`
+                    set cat_status = ${status}
 
-                    ps ${lock_proc} >& /dev/null
-                    set ps_status = "${status}" 
+                    if (${cat_status}) then 
+                        # Happens! But just grabbing the lock is not safe. 
+                        ${VERBOSE_ECHO} "${VERBOSE_INDENT}Lock file ${lock_file} disappeared! Getting back in the queue."
+                        continue
+                    else
+                        set lock_proc = `echo ${lock_id} | ${IVI_SED} 's/^.*-//'`
+                        if (${status}) then 
+                            ${P_STDERR} "Script ivi_lock_remove sed command failed. This should never happen."
+                            exit 1
+                        endif 
+                    endif 
 
-                    if (${ps_status}) then
+                    set remove_lock_file = 0
+
+                    # If the contents is bogus, then the ps below will fail. But if
+                    # it is empty, ps will not fail. So we check here. We expect
+                    # this is rare.
+                    
+                    if ("${lock_proc}" == "") then
                         echo ${requesting_pid} >! ${lock_file}
+                        ${WRN_ECHO} "Cannot read a process id from lock file. Assuming it needs to be removed."
+                        set remove_lock_file = 1
+                    else
+                        ${VERBOSE_ECHO_2} "${VERBOSE_INDENT}Lock handler for ${requesting_pid} checking on lock file process ${lock_proc} on iteration ${count}." 
+                        ps ${lock_proc} >& /dev/null
+                        set ps_status = "${status}" 
 
-                        ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process $$ resetting lock file ${lock_file} for process ${requesting_pid} as process ${lock_proc} does not exist."
+                        if (${ps_status}) then
+                            ${VERBOSE_ECHO} "${VERBOSE_INDENT}Lock handler for ${requesting_pid} reports process ${lock_proc} holding ${lock_file} no longer exists."
+                            set remove_lock_file = 1
+                        endif 
+                    endif 
 
-                        set got_it = 1
-                        break
-                    # else if (${count} > ${lock_wait_iterations}) then
+
+                    if (${remove_lock_file}) then
+                        # OK it is stale, but danger, others might be trying to
+                        # remove it too! So we do a mini lock for removing, but
+                        # not by recursing into the ivi lock system! 
+
+                        set rm_lock_file = "${lock_file}-RM-${lock_proc}"
+                        
+                        ${MAKE_SCRIPT_PATH}atomic_echo ${rm_lock_file} "${id}" 
+                        set atomic_echo_status =  ${status}
+
+                        if (${atomic_echo_status}) then
+                            ${VERBOSE_ECHO} "${VERBOSE_INDENT}Lock handler for ${requesting_pid} failed to get lock for removing a lock. No action taken."
+                        else 
+                            ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process ${requesting_pid} lock handler has got the lock file ${rm_lock_file} (contents `cat ${rm_lock_file}`)."
+                            
+                            # Check the file still exists and still has stale
+                            # contents.
+
+                            set really_remove_lock_file = 0
+
+                            if (-e "${lock_file}") then
+                                set new_lock_proc = `cat ${lock_file} | ${IVI_SED} 's/^.*-//'`
+
+                                if (! ${status}) then
+                                    # This covers both the case that the file is
+                                    # still empty, and it contains a dead
+                                    # process.
+
+                                    if (${new_lock_proc} == ${lock_proc}) then
+                                        set really_remove_lock_file = 1
+                                    endif
+                                endif 
+                            endif 
+
+                            if (${really_remove_lock_file}) then
+                                ${IVI_RM} "${lock_file}"
+                                ${VERBOSE_ECHO} "${VERBOSE_INDENT}Script ivi_lock_create removed lock file ${lock_file} as process ${lock_proc} does not exist."
+                            else
+                                ${VERBOSE_ECHO} "${VERBOSE_INDENT}Script ivi_lock_create not removing lock file ${lock_file} as it seems that someone else did it."
+                            endif 
+
+                            ${IVI_RM} "${rm_lock_file}"
+                            ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process ${requesting_pid} lock handler has relinquished the lock file ${rm_lock_file}."
+
+                            continue
+                        endif
                     else if (${time_waited} > ${max_time_to_wait}) then
-                        echo "Process $$ waited too long for ${lock_file} on behalf of process ${requesting_pid}. "
-                        echo "Process $$ waited for ${time_waited} X 0.01 seconds, exceeding the limit of ${max_time_to_wait} X 0.01 seconds."
+                        ${P_STDERR} "Process $$ waited too long for ${lock_file} on behalf of process ${requesting_pid}. "
+                        ${P_STDERR} "Process $$ waited for ${time_waited} X 0.01 seconds, exceeding the limit of ${max_time_to_wait} X 0.01 seconds."
                         set end_time = `date +%H:%M:%S`
-                        echo "Specifically it waited from ${start_time} to ${end_time}." 
-                        echo "Information about the process (${lock_proc}) holding the lock:"
+                        ${P_STDERR} "Specifically it waited from ${start_time} to ${end_time}." 
+                        ${P_STDERR} "Information about the process (${lock_proc}) holding the lock:"
                         ps -l ${lock_proc} 
-                        echo "Information about the process (${requesting_pid}) requesting the lock:"
+                        ${P_STDERR} "Information about the process (${requesting_pid}) requesting the lock:"
                         ps -l ${requesting_pid} 
 
                         if ($?EXIT_ON_LOCK_TIMEOUT) then
-                            echo "Process $$ waiting for ${lock_file} exiting with failure because EXIT_ON_LOCK_TIMEOUT is set." 
+                            ${P_STDERR} "Process $$ waiting for ${lock_file} exiting with failure because EXIT_ON_LOCK_TIMEOUT is set." 
                             set exit_status = 1
                             goto cleanup
                         endif 
 
-                        echo "Sleeping for 5 seconds for debugging" 
+                        ${P_STDERR} "Sleeping for 5 more seconds for debugging" 
                         sleep 5
-                        echo "Ignoring the lock."
+                        ${P_STDERR} "Ignoring the lock."
                         echo ${requesting_pid} >! ${lock_file}
                         set got_it = 1
                         break
                     endif
                 else
-                    ${VERBOSE_ECHO_2} "${VERBOSE_INDENT}Process $$ not checking up on lock file process ${lock_proc} on iteration ${count}." 
+                    ${VERBOSE_ECHO_2} "${VERBOSE_INDENT}Lock handler for ${requesting_pid} not checking up on lock file process on iteration ${count}." 
                 endif 
 
-                ${VERBOSE_ECHO_2} "${VERBOSE_INDENT}Process $$ waiting for ${lock_file} held on behalf of process ${lock_proc}."
+                ${VERBOSE_ECHO_2} "${VERBOSE_INDENT}Lock handler for ${requesting_pid} waiting for ${lock_file}."
+                ${VERBOSE_ECHO_2} "${VERBOSE_INDENT}Lock handler for ${requesting_pid} sleeping for ${sleep_time} seconds"
 
-                # Add some fractional seconds to reduce the chances of everyone
-                # wanting to start at the same time.
-                set x = ${requesting_pid} ; @ x %= 100 ; set sleep_time = "0.${x}"
-
-                ${VERBOSE_ECHO_2} "${VERBOSE_INDENT}Process $$ sleeping for ${sleep_time} seconds"
-                ${VERBOSE_ECHO_2} "${VERBOSE_INDENT}Process $$ slept ${time_waited}/${max_time_to_wait} x .01 seconds."
                 sleep ${sleep_time} >& /dev/null
-
-                @ time_waited += $x
-
                 if (${status}) then
                     ${P_STDERR} "Fractional sleep failed in ivi_lock_create." 
                     set exit_status = 1
                     goto cleanup
-                
                 endif
+
+                @ time_waited += ${w}
+                ${VERBOSE_ECHO_2} "${VERBOSE_INDENT}Lock handler for ${requesting_pid} slept ${time_waited}/${max_time_to_wait} x 0.01 seconds."
 
                 @ count ++
             end
-
-            # If we got_it is still false, then the lock file was removed by the
-            # process we were waiting on.
-            #
-            if (! ${got_it}) then
-                echo ${requesting_pid} >! ${lock_file}
-                ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process $$ setting lock file ${lock_file} for process ${requesting_pid} as the lock file no longer exists."
-            endif 
         endif 
 
-        # Check for clash. I have not found a safe way to ignore error output. 
-        set lock_proc = `cat ${lock_file}` 
-        if (${status}) then
-            # Could happen.
-            ${VERBOSE_ECHO} "${VERBOSE_INDENT}Lock file ${lock_file} disappeared. Trying again to get the lock."
-        else if (${lock_proc} != ${requesting_pid}) then 
-            ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process ${lock_proc} beat us to the lock on ${lock_file}. Resuming waiting."
-        else 
-            break
-        endif 
+        if (${got_it}) break
     end
 
     ${VERBOSE_ECHO} "${VERBOSE_INDENT}Process $$ set lock with label ${lock_label} for process ${requesting_pid} in `pwd`."
