r25496 | kobus | 2020-06-14 06:11:00 -0700 (Sun, 14 Jun 2020) | 5 lines
KJB --> IVI

Recorded result of commands processed by svn in /home/ivilab/repo_sync/ivilab_src_local/src/Make:
Updating '.':
U    BUILD_ENV
U    init_scripts
U    init_compile
U    Makefile-2
U    Makefile
U    util/build
U    util/Makefile
U    Makefile-library
U    Makefile-shared
U    Makefile-program
U    init_ua_hpc
U    Makefile-include-xxx
U    Makefile-makefile-dirs
U    init_machine
U    init_tacc_hpc
D    scripts/kjb_svn_rm
D    scripts/kjb_lock
D    scripts/kjb_add_makefiles
D    scripts/kjb_makedepend
U    scripts/regress_program
U    scripts/clean_global
U    scripts/clean_cache
U    scripts/get_local_include_dirs
U    scripts/build_makefile_dirs
U    scripts/echo_unless_quiet
U    scripts/finish_executable
U    scripts/build_sub_libs_needed
U    scripts/copy_if_not_empty
U    scripts/create_library
U    scripts/build_test_depend_2
U    scripts/build_test_depend_3
U    scripts/export_machine_vars
U    scripts/clean_build
U    scripts/test_program
U    scripts/echo_ld_path
U    scripts/stream_prog_lib_obs
U    scripts/clean_obj
U    scripts/build_include_lines_2
U    scripts/test_older_than
D    scripts/test/test_kjb_lock
D    scripts/test/test_kjb_lock_2
A    scripts/test/test_ivi_lock
A    scripts/test/test_ivi_lock_2
U    scripts/clean_src
U    scripts/build_makefile_libs_needed_2
U    scripts/create_program
U    scripts/update_include_line_file
U    scripts/build-2
A    scripts/ivi_lock
U    scripts/build
U    scripts/echo_machine
U    scripts/stream_script_names
A    scripts/ivi_makedepend
U    scripts/make_src_dist
U    scripts/build_makefile_libs_needed
U    scripts/build_file_list_2
U    scripts/build_incl_dot_h
U    scripts/do_ctags
U    scripts/define_build_aliases.sh
U    scripts/test_program_2
U    scripts/build_file_list
U    scripts/self_update
U    scripts/fix_incl
U    scripts/get_link_target
A    scripts/ivi_svn_rm
U    scripts/Makefile-2
U    scripts/stream_file_names
U    scripts/Makefile
U    scripts/copy_if_different
A    scripts/ivi_add_makefiles
U    scripts/echo_if_verbose
U    scripts/init_compile.sh
U    scripts/make_src_shadow_dir
U    scripts/make_link
U    scripts/build_include_lines
U    scripts/clean_local
U    scripts/build_makefile_dirs_2
U    scripts/touch_if_exists
U    Makefile-test
U    build_with_cmake
U    build_with_configure
U    Makefile-defs
U    build
U    Makefile-2-xxx
U    build_imported
Updated to revision 25496.

diff --git a/Make/scripts/test_program b/Make/scripts/test_program
--- a/Make/scripts/test_program
+++ b/Make/scripts/test_program
@@ -29,7 +29,7 @@ if ("${1}" == "-i") then
         set try_input_dir = `printf '%02d' ${count}`
         set try_input_dir_rel_path = "test_input/${program}/${try_input_dir}"
         if (! -e "${try_input_dir_rel_path}") then
-            ${KJB_MKDIR} "${try_input_dir_rel_path}"
+            ${IVI_MKDIR} "${try_input_dir_rel_path}"
             if ($status) break
             set input_dir = "${try_input_dir}"
             break
@@ -96,17 +96,17 @@ set run_dir = test_runs/${program}/${input_dir}/${test_type_dir}/${output_leaf_d
 # touched below. 
 #
 # if ("${test_type}" == "check") then
-#     ${KJB_RM} "${run_dir}/FAILED"
+#     ${IVI_RM} "${run_dir}/FAILED"
 # else if ("${test_type}" == "test") then
-#     ${VERBOSE_ECHO} "Script test_program is exectuting: kjb_svn_rm ${run_dir}"
-#     ${MAKE_SCRIPT_PATH}kjb_svn_rm "${run_dir}"
+#     ${VERBOSE_ECHO} "Script test_program is exectuting: ivi_svn_rm ${run_dir}"
+#     ${MAKE_SCRIPT_PATH}ivi_svn_rm "${run_dir}"
 # else if ("${test_type}" == "svn") then
 #     ${VERBOSE_ECHO} "Script test_program is leaving ${run_dir} alone due to test_type svn."
 # else 
-#     ${KJB_RM} "${run_dir}"
+#     ${IVI_RM} "${run_dir}"
 # endif 
 
-${KJB_MKDIR} "${run_dir}"
+${IVI_MKDIR} "${run_dir}"
  
 if ($status) then
     ${P_STDERR} "Script test_program unable to create directory ${run_dir} in `pwd`"
@@ -116,11 +116,11 @@ endif
 if ("${test_type}" == "test") then
     # We want to be able to remove all files that we did not modify, as they
     # might be stale. 
-    ${KJB_TOUCH} ${run_dir}/test_time_stamp
+    ${IVI_TOUCH} ${run_dir}/test_time_stamp
 endif 
 
-if ($?KJB_VERBOSE) then
-    if ($KJB_VERBOSE >= 2) then
+if ($?IVI_VERBOSE) then
+    if ($IVI_VERBOSE >= 2) then
         echo "Script test_program calling test_program_2 with args: "
         echo "    test_type:  ${test_type}"
         echo "    program:    ${program}"
@@ -139,13 +139,13 @@ else
     ${MAKE_SCRIPT_PATH}/test_program_2 "${test_type}" "${program}" "${input_dir}" "${obj_dir}" "${code_dir}" "${run_dir}" "${extra_args}" >& ${run_dir}/${test_type}.res 
     set test_status = ${status}
     
-    ${KJB_CAT} ${run_dir}/${test_type}.res 
+    ${IVI_CAT} ${run_dir}/${test_type}.res 
 endif
 
 if (${test_status}) then
-    ${KJB_TOUCH} "${run_dir}/FAILED"
+    ${IVI_TOUCH} "${run_dir}/FAILED"
 else 
-    ${KJB_RM} "${run_dir}/FAILED"
+    ${IVI_RM} "${run_dir}/FAILED"
 endif 
 
 exit ${test_status}
