r25863 | kobus | 2020-10-19 08:10:34 -0700 (Mon, 19 Oct 2020) | 5 lines
Fixed a build documentation bug (in c2man_in.c).
Intermediate commit for cleaning up testing scripts (not finished!).
Some adjustments to diagnosics.

Recorded result of commands processed by svn in /home/ivilab/repo_sync/ivilab_src_local/src/Make:
Updating '.':
U    init_compile
U    util/c2man_in.c
U    util/Makefile
U    Makefile-library
U    scripts/build-2
U    scripts/ivi_lock_remove
U    scripts/ivi_lock_for_make
U    scripts/atomic_echo
U    scripts/make_ivi
U    scripts/ivi_lock
U    scripts/finish_executable
U    scripts/ivi_lock_create
U    scripts/test_program_2
U    Makefile-program
Updated to revision 25863.

diff --git a/Make/init_compile b/Make/init_compile
--- a/Make/init_compile
+++ b/Make/init_compile
@@ -1,6 +1,6 @@
 # -----------------------------------------------------------------------------
 #
-# $Id: init_compile 25857 2020-10-12 19:36:45Z kobus $
+# $Id: init_compile 25863 2020-10-19 15:10:34Z kobus $
 # 
 # Optional libraries. 
 #     The main reason to edit this file is to add optional libraries.  Each
@@ -17,7 +17,8 @@
 #     help if you are having trouble.  One example is that the library you are
 #     adding depends on another one. In this case, the dependency should already
 #     have been processed so that you can check on its existence. See, for
-#     example, LIB_LEVMAR which depends on LIB_LAPACK.
+#     example, LIB_LEVMAR which depends on LIB_LAPACK. Another non-standard case
+#     is for header only libraries. See, for example, LIB_PB
 # 
 #     Do a similar thing in Make/Makefile-defs, copying all strings that have
 #     XXX in them, and changing XXX to a string corresponding to the variable
@@ -193,9 +194,9 @@ else if (-d "/bin_gcc_preferred") then
     setenv PATH "/bin_gcc_preferred:${PATH}" 
 endif 
 
-${VERBOSE_ECHO} 
-${VERBOSE_ECHO} PATH for build is: ${PATH}
-${VERBOSE_ECHO} 
+${VERBOSE_ECHO_2} 
+${VERBOSE_ECHO_2} PATH for build is: ${PATH}
+${VERBOSE_ECHO_2} 
 
 ################################################################################
 
@@ -402,14 +403,14 @@ if ($do_cache ) then
                 # Providing some output (below) and an alternative for
                 # experimentation.
                 #
-                ${VERBOSE_ECHO} "Using alternative method for loading ALL_LIBS from cache."
+                ${VERBOSE_ECHO_2} "Using alternative method for loading ALL_LIBS from cache."
 
                 $IVI_CAT $cache_fname | grep ALL_LIBS > "${USER_TEMP_PATH}ivi_env.setenv_all_libs"
                 source "${USER_TEMP_PATH}ivi_env.setenv_all_libs"
 
                 if ($?ALL_LIBS) then 
-                    ${VERBOSE_ECHO} "Loading of ALL_LIBS from cache succeeded."
-                    ${VERBOSE_ECHO} "ALL_LIBS: ${ALL_LIBS}"
+                    ${VERBOSE_ECHO_2} "Loading of ALL_LIBS from cache succeeded."
+                    ${VERBOSE_ECHO_2} "ALL_LIBS: ${ALL_LIBS}"
                 else 
                     setenv ALL_LIBS ""
                     ${VERBOSE_ECHO} "Loading of ALL_LIBS from cache failed. Setting ALL_LIBS to empty string."
@@ -452,7 +453,7 @@ if ($do_cache ) then
             # environment variables by unsetting any variables we set above
             unsetenv ALL_LIBS
         else 
-            ${VERBOSE_ECHO} "Using already up to date cache file: ${cache_fname}."
+            ${VERBOSE_ECHO_2} "Using already up to date cache file: ${cache_fname}."
 
             source ${cache_fname}
             # We could be caching the fact that this fails. 
@@ -488,10 +489,10 @@ if ($do_cache ) then
                 endif
             endif
 
-            if ($?DO_CACHE_LOCK) then
-                ${VERBOSE_ECHO} "Removing the cache lock" 
-                ${MAKE_SCRIPT_PATH}ivi_lock_remove init_compile
-            endif
+#             if ($?DO_CACHE_LOCK) then
+#                 ${VERBOSE_ECHO_2} "Removing the cache lock" 
+#                 ${MAKE_SCRIPT_PATH}ivi_lock_remove init_compile
+#             endif
 
             ${VERBOSE_ECHO} "Early exit (status ${exit_status}) from init_compile due to cache being OK."
             goto very_end_of_script
@@ -9877,10 +9878,8 @@ if ((! ${NO_LIBS}) && ("${IVI_HAVE_PYTHON}" != "")) then
         set ivi_have_pybind11 = "-DIVI_HAVE_PYBIND11"
         set lib_pybind11 = ""
 
-#         # We depend on python headers. But do not link! 
-         set pybind11_inc_dir = "${pybind11_inc_dir}:${python_inc_dir}"
-#         set lib_pybind11 = "${lib_python}" 
-#         set pybind11_load_dir = "${python_load_dir}"
+        # We depend on python headers. But do not link! 
+        set pybind11_inc_dir = "${pybind11_inc_dir}:${python_inc_dir}"
        
         set needed_inc_dirs = "${needed_inc_dirs} ${pybind11_inc_dir}"
 
@@ -9905,8 +9904,8 @@ if ($?IVI_VERBOSE) then
     echo ""
     if (${NO_LIBS}) then
         echo "Script init_compile skipped LIB_PYBIND11 due to NO_LIBS"
-#     else if ("${IVI_HAVE_PYTHON}" == "") then
-#         echo "Script init_compile skipped LIB_PYBIND11 due to missing dependency (python)"
+    else if ("${IVI_HAVE_PYTHON}" == "") then
+        echo "Script init_compile skipped LIB_PYBIND11 due to missing dependency (python)"
     else if ("${IVI_HAVE_PYBIND11}" != "") then
         echo "Script init_compile found PYBIND11 headers"
         echo "    PYBIND11  |  LIB_PYBIND11: ${LIB_PYBIND11}"
@@ -9933,8 +9932,9 @@ endif
 # This template is for object code libraries (not header only libraries). If you
 # hack it for a header only library then you need to add the string "DUMMY" to
 # the library list. See the script code for pybind11 header file only library.
-# (The boost header only script code is more complex because we support multiple
-# versions of boost simulaneously). 
+# (You probably want to avoid studying the boost header only library script code
+# as it is more complex because we support multiple versions of boost
+# simulaneously). 
 #
 # Don't forget to update Makefile-defs, Makefile-program, IVI/Makefile-2, and
 # IVI_cpp/Makefile-2 (see comment block at the begining of this file). 
@@ -9960,7 +9960,7 @@ set xxx_load_dir = ""
 # be "" which has no effect. Most modules do not even do this because we just
 # started doing it this way. If you are confident this library does not, and
 # will not, ever have dependencies, then you could skip this. However, perhaps
-# this library depends on OPENCV and LAPACK. Then:
+# this library depends on OPENCV and LAPACK. Then we would use:
 #
 set dependencies = "OPENCV LAPACK"  
 set missing_dependencies = ""
@@ -10788,7 +10788,7 @@ endif
 very_end_of_script:
 
 if ($?DO_CACHE_LOCK) then
-    ${VERBOSE_ECHO} "Removing the cache lock" 
+    ${VERBOSE_ECHO_2} "Removing the cache lock" 
     ${MAKE_SCRIPT_PATH}ivi_lock_remove init_compile
 endif
 
@@ -10797,9 +10797,9 @@ unalias ivi_setenv
 if ($?IVI_VERBOSE) then
     set end_time = `date +%H:%M:%S`
     ${VERBOSE_ECHO} "Script init_compile finishing with status ${exit_status}"
-    ${VERBOSE_ECHO} "    Start time: ${start_time}"
-    ${VERBOSE_ECHO} "    End time:   ${end_time}"
-    ${VERBOSE_ECHO} " "
+    ${VERBOSE_ECHO_2} "    Start time: ${start_time}"
+    ${VERBOSE_ECHO_2} "    End time:   ${end_time}"
+    ${VERBOSE_ECHO_2} " "
 endif 
 
 exit ${exit_status}
diff --git a/Make/scripts/build-2 b/Make/scripts/build-2
--- a/Make/scripts/build-2
+++ b/Make/scripts/build-2
@@ -479,9 +479,21 @@ set need_depend = 0
 
 while ($count <=  ${num_args}) 
     set arg = $argv[${count}]
+    set test_without_input = 0
+
+    @ count ++
 
     foreach test_target_type (${test_target_prefixes} ${test_target_suffixes})
         set part_one = `echo $arg | sed "s/\.${test_target_type}${dollar}//"`
+
+        if ("${test_target_type}" == "${part_one}") then
+            if (! -d "test_input") then
+                ${ECHO_UNLESS_QUIET} "Build of target ${arg} exiting early in ${cwd} as there is no test_input directory."
+                set test_without_input = 1
+                break
+            endif 
+        endif 
+
         if ("${part_one}" != "${arg}") then
             ${VERBOSE_ECHO} "Changing arg '${arg}' to '${test_target_type}.${part_one}'"
             set arg = "${test_target_type}.${part_one}"
@@ -489,18 +501,28 @@ while ($count <=  ${num_args})
         endif
     end
 
+    if (${test_without_input}) continue
+
     foreach test_target_type (${test_target_prefixes} ${test_target_suffixes})
         set next_arg = `echo $arg | sed "s/${test_target_type}\.//"`
         if ("${next_arg}" != "${arg}") then
             ${VERBOSE_ECHO} "Breaking arg '${arg}' into '${test_target_type}' and '${next_arg}'"
             set arg = "${test_target_type}"
-            break
         else 
             set next_arg = ""
         endif 
+
+        if ("${test_target_type}" == "${arg}") then
+            if (! -d "test_input") then
+                ${ECHO_UNLESS_QUIET} "Build of target ${arg} exiting early in ${cwd} as there is no test_input directory."
+                set test_without_input = 1
+            endif 
+
+            break
+        endif 
     end
 
-    @ count ++
+    if (${test_without_input}) continue
 
     # If multiple make targets are being processed, then we need to make sure
     # that ones that forced settings do not affect the others. 
@@ -778,6 +800,12 @@ while ($count <=  ${num_args})
                     set arg = "${arg} test_runs/${prog}/${test_instance}/regress/${LD_OBJ_DIR}regression_test_passed"
                 end
             endif
+
+            if ("${arg}" == "") then
+                ${P_STDERR} "No regress instances found for ${prog}"
+                ${P_STDERR} " "
+                exit 1
+            endif 
         endif 
     else if ("${arg}" == "test_svn")  then
         # No need_depend because the test Makefiles are separated. But they do
@@ -805,9 +833,6 @@ while ($count <=  ${num_args})
                 exit 1
             endif 
         endif 
-    else if ( ("${arg}" == "regress")  || ("${arg}" == "regress_clean") )  then
-        # Probably need_depend_bootstrap would suffice. 
-        set need_depend = 1
     else if (("${arg}" == "test_clean") || ("${arg}" == "test_very_clean") || ("${arg}" == "test_invalid")  || ("${arg}" == "regress_clean"))  then
         set need_depend_bootstrap = 1
         
@@ -1032,9 +1057,9 @@ while (${try_count} <= 4)
                 ${MAKE_SCRIPT_PATH}build_library_makefile_2 
 
                 if (${status}) then
-                    set exit_status = 1
-                    ${P_STDERR} "Building Makefile-2 in ${cwd} failed."
                     # If this fails, it is not likely that retry will help. 
+                    ${P_STDERR} "Building Makefile-2 in ${cwd} failed."
+                    set exit_status = 1
                     break
                 else 
                     ${VERBOSE_ECHO_2} "Script build-2 successfully rebuilt ${cwd}/Makefile-2."
@@ -1084,9 +1109,9 @@ while (${try_count} <= 4)
                 ${MAKE_SCRIPT_PATH}build_makefile_include 
 
                 if (${status}) then
-                    set exit_status = 1
-                    ${P_STDERR} "Building Makefile-include in ${cwd} failed."
                     # If this fails, it is not likely that retry will help. 
+                    ${P_STDERR} "Building Makefile-include in ${cwd} failed."
+                    set exit_status = 1
                     break
                 else 
                     ${VERBOSE_ECHO_2} "Script build-2 successfully rebuilt ${cwd}/Makefile-include."
@@ -1359,18 +1384,26 @@ while (${try_count} <= 4)
         ${ivi_depend_make} -f Makefile-2 Makefile |& ${IVI_TEE} ${make_log_file}
         if (${status}) then
             ${P_STDERR} "Initial build of 'Makefile' failed in ${cwd}."
-            if ($?SKIP_DEPEND_RETRY) then
-                ${P_STDERR} "Skipping trying again because SKIP_DEPEND_RETRY is set." 
-                set exit_status = 1
-                break
-            else 
+#             if ($?SKIP_DEPEND_RETRY) then
+#                 ${P_STDERR} "Skipping trying again because SKIP_DEPEND_RETRY is set." 
+#                 set exit_status = 1
+#                 break
+#             else 
                 ${P_STDERR} "Trying some more times as it likely means that we are missing some rebuildable makefiles."
-            endif 
+#             endif 
 
             if ($?LOG_MAKE) set make_log_file = "${MAKE_LOG_PATH}make_Makefile_${try_count}_2.res"
             ${ivi_depend_make} -f Makefile-2 Makefile |& ${IVI_TEE} ${make_log_file}
             if (${status}) then
                 ${P_STDERR} "Second build of 'Makefile' failed in ${cwd}, but often it needs to be done three times. " 
+
+                if ($?SKIP_DEPEND_RETRY) then
+                    ${P_STDERR} "Skipping trying again because SKIP_DEPEND_RETRY is set." 
+                    set exit_status = 1
+                    break
+                else 
+                    ${P_STDERR} "Trying again as it sometimes needs to be done three times. " 
+                endif 
 
                 if ($?LOG_MAKE) set make_log_file = "${MAKE_LOG_PATH}make_Makefile_${try_count}_3.res"
                 ${ivi_depend_make} -f Makefile-2 Makefile |& ${IVI_TEE} ${make_log_file}
@@ -1501,13 +1534,11 @@ while (${try_count} <= 4)
             pushd ${MAKE_PATH} > /dev/null
                 pushd util > /dev/null
                     pushd c2man-2.40-kobus > /dev/null
-                        if ($?IVI_VERBOSE) then
-                            echo " "
-                            echo "Script build-2 is building utilities in ${cwd}." 
-                        endif 
+                        ${VERBOSE_ECHO} " "
+                        ${VERBOSE_ECHO} "Script build-2 is building c2man in ${cwd}." 
                          
                         if ($?DRY_RUN) then
-                            echo "DRY: (setenv IVI_CC ''; setenv PRODUCTION 1; setenv BUILD_BIN_PATH ${MAKE_BIN_PATH}; source ${MAKE_PATH}init_compile; ${IVI_MAKE_SERIAL} bin)"
+                            echo "DRY: (setenv CURRENT_PATH ${cwd}/; setenv IVI_CC ''; setenv PRODUCTION 1; setenv BUILD_BIN_PATH ${MAKE_BIN_PATH}; source ${MAKE_PATH}init_compile; ${IVI_MAKE_SERIAL} bin)"
                         else
                             if ($?LOG_MAKE) set make_log_file = "${MAKE_LOG_PATH}make_c2man_bin_${try_count}.res"
 
@@ -1522,7 +1553,7 @@ while (${try_count} <= 4)
                             # it at some point to be more consistent with other
                             # program dirs. 
                             #
-                            (   setenv IVI_CC ""; setenv PRODUCTION 1; setenv BUILD_BIN_PATH "${MAKE_BIN_PATH}"; \
+                            (   setenv CURRENT_PATH "${cwd}/"; setenv IVI_CC ""; setenv PRODUCTION 1; setenv BUILD_BIN_PATH "${MAKE_BIN_PATH}"; \
                                 source ${MAKE_PATH}init_compile; \
                                 if ("${IVI_CC}" != "${save_ivi_cc}") ${WARN_ECHO} "Switching compiler from ${save_ivi_cc} to ${IVI_CC} for doc utilities"; \
                                 ${IVI_MAKE_SERIAL} bin \
@@ -1541,7 +1572,7 @@ while (${try_count} <= 4)
                         ${VERBOSE_ECHO} "Script build-2 is building utilities in ${cwd}." 
 
                         if ($?DRY_RUN) then
-                            echo "DRY: (setenv IVI_CC ''; setenv PRODUCTION 1; setenv BUILD_BIN_PATH ${MAKE_BIN_PATH}; source ${MAKE_PATH}init_compile; ${IVI_MAKE_SERIAL} -f Makefile-2 bin)"
+                            echo "DRY: (setenv CURRENT_PATH ${cwd}/; setenv IVI_CC ''; setenv PRODUCTION 1; setenv BUILD_BIN_PATH ${MAKE_BIN_PATH}; source ${MAKE_PATH}init_compile; ${IVI_MAKE_SERIAL} -f Makefile-2 bin)"
                         else
                             if ($?LOG_MAKE) set make_log_file = "${MAKE_LOG_PATH}make_util_bin_${try_count}.res"
 
@@ -1549,7 +1580,7 @@ while (${try_count} <= 4)
                             # compiler and production mode. The setting of IVI_CC to empty asks
                             # init_compile to choose the compiler. 
                             #
-                            (   setenv IVI_CC ""; setenv PRODUCTION 1; setenv BUILD_BIN_PATH "${MAKE_BIN_PATH}"; \
+                            (   setenv CURRENT_PATH "${cwd}/"; setenv IVI_CC ""; setenv PRODUCTION 1; setenv BUILD_BIN_PATH "${MAKE_BIN_PATH}"; \
                                 source ${MAKE_PATH}init_compile; \
                                 if ("${IVI_CC}" != "${save_ivi_cc}") ${WARN_ECHO} "Switching compiler from ${save_ivi_cc} to ${IVI_CC} for doc utilities"; \
                                 ${IVI_MAKE_SERIAL} -f Makefile-2 bin |& ${suppress_jobserver_msg} |& ${IVI_TEE} ${make_result_temp_file} |& ${IVI_TEE} ${make_log_file} \
@@ -1696,12 +1727,16 @@ while (${try_count} <= 4)
                     ${IVI_MAKE} -q ${prog} -f Makefile-2 |& ${suppress_jobserver_msg}
                     if (! ${status}) then
                         if ( ! $?IVI_QUIET ) then
-                            echo "Script build-2 reports target [ ${prog} ] is up to date."
+                            echo "Script build-2 reports prerequisite ${prog} for target ${arg} is up to date."
                         endif 
                     else 
                         if ($?DRY_RUN) then
                             echo "DRY: ${IVI_MAKE} -f Makefile-2 ${prog} |& ${suppress_jobserver_msg}"
                         else
+                            if ( ! $?IVI_QUIET ) then
+                                echo "Script build-2 building prerequisite ${prog} for target ${arg}."
+                            endif 
+
                             if ($?LOG_MAKE) set make_log_file = "${MAKE_LOG_PATH}make_prog_${try_count}.res"
                             ${IVI_MAKE} -f Makefile-2 ${prog} |& ${suppress_jobserver_msg} |& ${IVI_TEE} ${make_result_temp_file} |& ${IVI_TEE} ${make_log_file}
                             set make_status = ${status}
